/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tercerproyecto;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jenny
 */
public class IngresarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ingresarEmpleado
     */
    // Variable que define qué base de datos usar
    private boolean usarMySQL;
    private PostgreSQLConnect postgreSQLConnect;
    private MySQLConnect mySQLConnect;

    /**
     * Constructor de la clase
     *
     * @param usarMySQL Si es true, usará MySQL; si es false, usará PostgreSQL
     */
    public IngresarEmpleado(boolean usarMySQL) {
        this.usarMySQL = usarMySQL;
        postgreSQLConnect = new PostgreSQLConnect();
        mySQLConnect = new MySQLConnect();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        txtTercerNombre = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtSegundoApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefonoCasa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTelefonoMovil = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSalarioBase = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBonificacion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(476, 700));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel1.setText("DPI empleado:");

        jLabel2.setText("Primer Nombre:");

        jLabel3.setText("Segundo Nombre:");

        jLabel4.setText("Tercer Nombre:");

        jLabel5.setText("Primer Apellido:");

        jLabel6.setText("Segundo Apellido:");

        jLabel7.setText("Dirección:");

        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });

        txtPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerNombreActionPerformed(evt);
            }
        });

        txtSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoNombreActionPerformed(evt);
            }
        });

        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });

        txtTelefonoCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoCasaActionPerformed(evt);
            }
        });

        jLabel8.setText("Teléfono Residencia:");

        jLabel9.setText("Teléfono Móvil:");

        txtTelefonoMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoMovilActionPerformed(evt);
            }
        });

        jLabel10.setText("Sueldo:");

        jLabel11.setText("Bonificación:");

        txtBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBonificacionActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Modficar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Ingreso Empleado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDPI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(txtSegundoNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTercerNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrimerApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSegundoApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSalarioBase, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtBonificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTercerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefonoCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTelefonoMovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtSalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnRegresar))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // Verificar si alguno de los campos de texto está vacío
        if (txtDPI.getText().isEmpty() || txtPrimerNombre.getText().isEmpty()
                || txtSegundoNombre.getText().isEmpty()
                || txtPrimerApellido.getText().isEmpty() || txtSegundoApellido.getText().isEmpty()
                || txtDireccion.getText().isEmpty() || txtTelefonoCasa.getText().isEmpty()
                || txtTelefonoMovil.getText().isEmpty() || txtSalarioBase.getText().isEmpty()
                || txtBonificacion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos de nuevo empleado", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Empleado empleado = new Empleado();
        empleado.setDpi(txtDPI.getText());
        empleado.setPrimerNombre(txtPrimerNombre.getText());
        empleado.setSegundoNombre(txtSegundoNombre.getText());
        empleado.setTercerNombre(txtTercerNombre.getText());
        empleado.setPrimerApellido(txtPrimerApellido.getText());
        empleado.setSegundoApellido(txtSegundoApellido.getText());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setTelefonoResidencia(txtTelefonoCasa.getText());
        empleado.setTelefonoMovil(txtTelefonoMovil.getText());
        empleado.setSueldo(Double.valueOf(txtSalarioBase.getText()));
        empleado.setBonificacion(Double.valueOf(txtBonificacion.getText()));
        try {
            boolean success;
            if (usarMySQL) {
                mySQLConnect.establecerConexion();
                success = mySQLConnect.insertarEmpleado(empleado);
            } else {
                postgreSQLConnect.establecerConexion();
                success = postgreSQLConnect.insertarEmpleado(empleado);
            }

            if (success) {
                JOptionPane.showMessageDialog(null, "Empleado insertado correctamente.", "INFO MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Ocurrió un error al insertar el empleado.", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Limpiar campos despues de guardar
        LimpiarCamposTexto();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtDPI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: Ingrese un número de DPI.");
            return;
        }
        String dpi = txtDPI.getText();
        try {
            Empleado empleado;
            if (usarMySQL) {
                mySQLConnect.establecerConexion();
                empleado = mySQLConnect.buscarEmpleado(dpi);
            } else {
                postgreSQLConnect.establecerConexion();
                empleado = postgreSQLConnect.buscarEmpleado(dpi);
            }

            if (empleado != null) {
                txtPrimerNombre.setText(empleado.getPrimerNombre());
                txtSegundoNombre.setText(empleado.getSegundoNombre());
                txtTercerNombre.setText(empleado.getTercerNombre());
                txtPrimerApellido.setText(empleado.getPrimerApellido());
                txtSegundoApellido.setText(empleado.getSegundoApellido());
                txtDireccion.setText(empleado.getDireccion());
                txtTelefonoCasa.setText(empleado.getTelefonoResidencia());
                txtTelefonoMovil.setText(empleado.getTelefonoMovil());
                txtSalarioBase.setText(empleado.getSueldo().toString());
                txtBonificacion.setText(empleado.getBonificacion().toString());
                JOptionPane.showMessageDialog(null, "Empleado encontrado.", "INFO MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Empleado no encontrado.", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Empleado empleado = new Empleado();
        empleado.setDpi(txtDPI.getText());
        empleado.setPrimerNombre(txtPrimerNombre.getText());
        empleado.setSegundoNombre(txtSegundoNombre.getText());
        empleado.setTercerNombre(txtTercerNombre.getText());
        empleado.setPrimerApellido(txtPrimerApellido.getText());
        empleado.setSegundoApellido(txtSegundoApellido.getText());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setTelefonoResidencia(txtTelefonoCasa.getText());
        empleado.setTelefonoMovil(txtTelefonoMovil.getText());
        empleado.setSueldo(Double.valueOf(txtSalarioBase.getText()));
        empleado.setBonificacion(Double.valueOf(txtBonificacion.getText()));
        try {
            boolean success;
            if (usarMySQL) {
                mySQLConnect.establecerConexion();
                success = mySQLConnect.modificarEmpleado(empleado);
            } else {
                postgreSQLConnect.establecerConexion();
                success = postgreSQLConnect.modificarEmpleado(empleado);
            }

            if (success) {
                JOptionPane.showMessageDialog(null, "Empleado actualizado correctamente.", "INFO MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el empleado con el DPI especificado.", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String dpi = txtDPI.getText();
        try {
            boolean success;
            if (usarMySQL) {
                mySQLConnect.establecerConexion();
                success = mySQLConnect.eliminarEmpleado(dpi);
            } else {
                postgreSQLConnect.establecerConexion();
                success = postgreSQLConnect.eliminarEmpleado(dpi);
            }

            if (success) {
                JOptionPane.showMessageDialog(null, "Empleado eliminado correctamente.", "INFO MESSAGE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al eliminar el empleado.", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(IngresarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Limpiar campos despues de guardar
        LimpiarCamposTexto();

    }//GEN-LAST:event_btnEliminarActionPerformed


    private void txtSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoNombreActionPerformed

    }//GEN-LAST:event_txtSegundoNombreActionPerformed

    private void txtPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerNombreActionPerformed

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void txtTelefonoCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoCasaActionPerformed

    private void txtTelefonoMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMovilActionPerformed

    private void txtBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBonificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBonificacionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        moduloPrincipal nuevoModulo = new moduloPrincipal();
        nuevoModulo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    //Método para limpiar campos
    public void LimpiarCamposTexto() {
        txtDPI.setText("");
        txtPrimerNombre.setText("");
        txtSegundoNombre.setText("");
        txtTercerNombre.setText("");
        txtPrimerApellido.setText("");
        txtSegundoApellido.setText("");
        txtDireccion.setText("");
        txtTelefonoCasa.setText("");
        txtTelefonoMovil.setText("");
        txtSalarioBase.setText("");
        txtBonificacion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBonificacion;
    public javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtPrimerApellido;
    public javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSalarioBase;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefonoCasa;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtTercerNombre;
    // End of variables declaration//GEN-END:variables
}
